/* data-testid estáveis para os testes E2E. Renomear um valor quebra os specs de e2e/.
   Auth: form-entrar, entrar-email, entrar-senha, entrar-enviar, link-cadastro,
   form-cadastro, cadastro-nome, cadastro-email, cadastro-senha, cadastro-nascimento, cadastro-lgpd,
   cadastro-enviar, botao-demo, erro-formulario, aviso-sessao.
   Onboarding: onboarding-vazio, onboarding-exemplo.
   Shell: shell-perfil, shell-perfil-nome, shell-responsavel, selo-convidado, botao-sair, botao-reiniciar, reinicio-confirmar,
   reinicio-zerar, estado-vazio, cta-primeiro-documento.
   Linha do tempo: evento-item, evento-detalhe, ia-explicar, ia-explicacao, evento-excluir,
   evento-excluir-confirmar, evento-excluido, busca-pergunta, busca-perguntar-copiloto.
   Fontes/conferência: fontes-texto, fontes-ler-texto, fontes-pdf, conferencia, conferencia-titulo,
   conferencia-salvar, conferencia-descartar, conferencia-identidade, conferencia-confirmo-meu,
   conferencia-confirmo-meu-rodape, conferencia-motivo, conferencia-ir-confirmacao.
   IA: copiloto-pergunta, copiloto-enviar, copiloto-resposta, ia-passos, ia-resumo, resumo-sintese.
   Compartilhamento: acesso-gerar, acesso-painel, acesso-codigo, acesso-validade, acesso-copiar, acesso-revogar, acesso-revogado.
   Médico: medico-form, medico-codigo, medico-profissional, medico-entrar, medico-erro, medico-paciente,
   medico-aviso, medico-evento, medico-pendencias, medico-ponto, medico-gerar-resumo, medico-resumo, medico-sair, medico-encerrado.
   Conta: perfil-form, perfil-salvar, perfil-salvo, excluir-confirmacao, excluir-botao, atalho-conta. */
export const TID = {
  formEntrar: 'form-entrar',
  entrarEmail: 'entrar-email',
  entrarSenha: 'entrar-senha',
  entrarEnviar: 'entrar-enviar',
  linkCadastro: 'link-cadastro',
  formCadastro: 'form-cadastro',
  cadastroNome: 'cadastro-nome',
  cadastroEmail: 'cadastro-email',
  cadastroSenha: 'cadastro-senha',
  cadastroNascimento: 'cadastro-nascimento',
  cadastroLgpd: 'cadastro-lgpd',
  cadastroEnviar: 'cadastro-enviar',
  botaoDemo: 'botao-demo',
  erroFormulario: 'erro-formulario',
  avisoSessao: 'aviso-sessao',

  onboardingVazio: 'onboarding-vazio',
  onboardingExemplo: 'onboarding-exemplo',

  shellPerfil: 'shell-perfil',
  shellPerfilNome: 'shell-perfil-nome',
  shellIniciais: 'shell-iniciais',
  shellResponsavel: 'shell-responsavel',
  seloConvidado: 'selo-convidado',
  botaoSair: 'botao-sair',
  botaoReiniciar: 'botao-reiniciar',
  reinicioConfirmar: 'reinicio-confirmar',
  reinicioZerar: 'reinicio-zerar',
  estadoVazio: 'estado-vazio',
  ctaPrimeiroDocumento: 'cta-primeiro-documento',

  eventoItem: 'evento-item',
  eventoDetalhe: 'evento-detalhe',
  eventoExcluir: 'evento-excluir',
  eventoExcluirConfirmar: 'evento-excluir-confirmar',
  eventoExcluido: 'evento-excluido',
  buscaPergunta: 'busca-pergunta',
  buscaPerguntarCopiloto: 'busca-perguntar-copiloto',
  iaExplicar: 'ia-explicar',
  iaExplicacao: 'ia-explicacao',

  fontesTexto: 'fontes-texto',
  fontesLerTexto: 'fontes-ler-texto',
  fontesPdf: 'fontes-pdf',
  conferencia: 'conferencia',
  conferenciaTitulo: 'conferencia-titulo',
  conferenciaSalvar: 'conferencia-salvar',
  conferenciaDescartar: 'conferencia-descartar',
  conferenciaIdentidade: 'conferencia-identidade',
  conferenciaConfirmoMeu: 'conferencia-confirmo-meu',
  conferenciaConfirmoMeuRodape: 'conferencia-confirmo-meu-rodape',
  conferenciaMotivo: 'conferencia-motivo',
  conferenciaIrConfirmacao: 'conferencia-ir-confirmacao',

  copilotoPergunta: 'copiloto-pergunta',
  copilotoEnviar: 'copiloto-enviar',
  copilotoResposta: 'copiloto-resposta',
  iaPassos: 'ia-passos',
  iaResumo: 'ia-resumo',
  resumoSintese: 'resumo-sintese',
  resumoPontos: 'resumo-pontos',
  resumoPonto: 'resumo-ponto',

  acessoGerar: 'acesso-gerar',
  acessoPainel: 'acesso-painel',
  acessoCodigo: 'acesso-codigo',
  acessoValidade: 'acesso-validade',
  acessoCopiar: 'acesso-copiar',
  acessoRevogar: 'acesso-revogar',
  acessoRevogado: 'acesso-revogado',

  medicoForm: 'medico-form',
  medicoCodigo: 'medico-codigo',
  medicoProfissional: 'medico-profissional',
  medicoEntrar: 'medico-entrar',
  medicoErro: 'medico-erro',
  medicoPaciente: 'medico-paciente',
  medicoAviso: 'medico-aviso',
  medicoEvento: 'medico-evento',
  medicoPendencias: 'medico-pendencias',
  medicoPonto: 'medico-ponto',
  medicoGerarResumo: 'medico-gerar-resumo',
  medicoResumo: 'medico-resumo',
  medicoSair: 'medico-sair',
  medicoEncerrado: 'medico-encerrado',

  perfilForm: 'perfil-form',
  perfilSalvar: 'perfil-salvar',
  perfilSalvo: 'perfil-salvo',
  excluirConfirmacao: 'excluir-confirmacao',
  excluirBotao: 'excluir-botao',
  atalhoConta: 'atalho-conta',
} as const
