import type { Evento } from '../../src/data/types.js'

/* Eventos do Marcos no shape exato que a extração real (OCI) devolveu para os PDFs de
   entrega/documentos-demo (d..) e e2e/fixtures/documentos (f..). Só o id foi acrescentado (o servidor
   devolve o evento sem id) e o campo novo, removido; d01 e d08 já com o prompt que pede conduta no
   resumo da consulta. Não editar à mão: é a evidência do formato real. */
export const DEMO_MARCOS: Evento[] = [
  {
    id: 'd01',
    data: '2024-08-14',
    tipo: 'consulta',
    titulo: 'Relatório de Consulta — Cardiologia',
    instituicao: 'Clínica Ipê-Roxo',
    fonte: 'paciente',
    especialidade: 'Cardiologia',
    resumo: 'O paciente foi encaminhado por pressão arterial elevada e refere cefaleia occipital ocasional. Foi diagnosticado com hipertensão arterial sistêmica estágio 1 e sobrepeso. Foi iniciada losartana potássica 50 mg e recomendada dieta com restrição de sódio e atividade física aeróbica. Foram solicitados exames como MAPA de 24 horas, perfil lipídico completo, glicemia de jejum, hemoglobina glicada, creatinina e potássio, com retorno em 60 dias.',
    sinal: 'alterado',
    medidas: [
      { nome: 'Pressão arterial', valor: 152, unidade: 'mmHg', refMax: 140, sinal: 'alterado' },
      { nome: 'Pressão arterial', valor: 96, unidade: 'mmHg', refMax: 90, sinal: 'alterado' },
      { nome: 'Frequência cardíaca', valor: 78, unidade: 'bpm', refMin: 60, refMax: 100, sinal: 'normal' },
      { nome: 'IMC', valor: 27.8, unidade: 'kg/m²', refMin: 18.5, refMax: 24.9, sinal: 'alterado' },
      { nome: 'Circunferência abdominal', valor: 98, unidade: 'cm', refMax: 94, sinal: 'alterado' },
    ],
    tags: ['hipertensão', 'sobrepeso'],
    origem: 'OCR + IA',
    confianca: 0.7,
    documento: '01-consulta-cardiologia-2024-08-14.pdf',
  },
  {
    id: 'd02',
    data: '2024-08-29',
    tipo: 'exame',
    titulo: 'Monitorizacao Ambulatorial da Pressao Arterial (MAPA 24 H)',
    instituicao: 'Instituto Cardiológico Sabiá',
    fonte: 'paciente',
    especialidade: 'Cardiologia',
    resumo: 'O exame registra as leituras de pressão arterial durante 24 horas, com médias pressóricas elevadas nos períodos de 24 horas, vigília e sono.',
    sinal: 'alterado',
    medidas: [
      { nome: 'PA sistólica média — 24 h', valor: 138, unidade: 'mmHg', refMax: 130, sinal: 'alterado' },
      { nome: 'PA diastólica média — 24 h', valor: 88, unidade: 'mmHg', refMax: 80, sinal: 'alterado' },
      { nome: 'PA sistólica média — vigília', valor: 143, unidade: 'mmHg', refMax: 135, sinal: 'alterado' },
      { nome: 'PA diastólica média — vigília', valor: 92, unidade: 'mmHg', refMax: 85, sinal: 'alterado' },
      { nome: 'PA sistólica média — sono', valor: 126, unidade: 'mmHg', refMax: 120, sinal: 'alterado' },
      { nome: 'PA diastólica média — sono', valor: 78, unidade: 'mmHg', refMax: 70, sinal: 'alterado' },
      { nome: 'Descenso noturno sistólico', valor: 12, unidade: '%', refMin: 10, refMax: 20, sinal: 'normal' },
      { nome: 'Frequência cardíaca média', valor: 76, unidade: 'bpm', refMin: 60, refMax: 100, sinal: 'normal' },
    ],
    tags: ['pressao arterial', 'cardiologia'],
    origem: 'OCR + IA',
    confianca: 0.9,
    documento: '02-mapa-24h-2024-08-29.pdf',
  },
  {
    id: 'd04',
    data: '2025-01-20',
    tipo: 'exame',
    titulo: 'Glicemia, Hemoglobina Glicada e Função Renal',
    instituicao: 'Laboratório Quaresmeira',
    fonte: 'paciente',
    resumo: 'Exame de glicemia, hemoglobina glicada e função renal com resultados para glicemia de jejum, hemoglobina glicada, creatinina, taxa de filtração glomerular estimada, ureia e potássio.',
    sinal: 'normal',
    medidas: [
      { nome: 'Glicemia de jejum', valor: 96, unidade: 'mg/dL', refMin: 70, refMax: 99, sinal: 'normal' },
      { nome: 'Hemoglobina glicada (HbA1c)', valor: 5.6, unidade: '%', refMin: 4, refMax: 5.6, sinal: 'normal' },
      { nome: 'Creatinina', valor: 0.94, unidade: 'mg/dL', refMin: 0.7, refMax: 1.3, sinal: 'normal' },
      { nome: 'Taxa de filtração glomerular estimada (TFG)', valor: 101, unidade: 'mL/min/1,73 m²', refMin: 90, sinal: 'normal' },
      { nome: 'Ureia', valor: 31, unidade: 'mg/dL', refMin: 15, refMax: 45, sinal: 'normal' },
      { nome: 'Potássio', valor: 4.4, unidade: 'mEq/L', refMin: 3.5, refMax: 5.1, sinal: 'normal' },
    ],
    tags: ['glicemia', 'hemoglobina glicada', 'função renal'],
    origem: 'OCR + IA',
    confianca: 0.9,
    documento: '04-glicemia-hba1c-funcao-renal-2025-01-20.pdf',
  },
  {
    id: 'd05',
    data: '2025-03-11',
    tipo: 'exame',
    titulo: 'Espirometria com prova broncodilatadora',
    instituicao: 'Clínica Ipê-Roxo',
    fonte: 'paciente',
    especialidade: 'Pneumologia',
    resumo: 'O exame de espirometria com prova broncodilatadora mostrou distúrbio ventilatório obstrutivo leve, com resposta significativa ao broncodilatador.',
    sinal: 'alterado',
    medidas: [
      { nome: 'CVF (capacidade vital forçada) pré-BD', valor: 4.12, unidade: 'L', refMin: 0, sinal: 'normal' },
      { nome: 'CVF (capacidade vital forçada) % do previsto pré-BD', valor: 88, unidade: '% do previsto', refMin: 80, sinal: 'normal' },
      { nome: 'VEF1 (volume expiratório forçado no 1º s) pré-BD', valor: 2.98, unidade: 'L', refMin: 0, sinal: 'normal' },
      { nome: 'VEF1 (volume expiratório forçado no 1º s) % do previsto pré-BD', valor: 78, unidade: '% do previsto', refMin: 80, sinal: 'alterado' },
      { nome: 'VEF1/CVF pré-BD', valor: 0.72, unidade: '', refMin: 0.75, sinal: 'alterado' },
      { nome: 'FEF 25-75% pré-BD', valor: 2.41, unidade: 'L/s', refMin: 0, sinal: 'normal' },
      { nome: 'FEF 25-75% % do previsto pré-BD', valor: 58, unidade: '% do previsto', refMin: 60, sinal: 'alterado' },
    ],
    tags: ['espirometria', 'asma'],
    origem: 'OCR + IA',
    confianca: 0.95,
    documento: '05-espirometria-2025-03-11.pdf',
  },
  {
    id: 'd08',
    data: '2025-11-04',
    tipo: 'consulta',
    titulo: 'Relatório de Consulta — Pneumologia',
    instituicao: 'Clínica Ipê-Roxo',
    fonte: 'paciente',
    especialidade: 'Pneumologia',
    resumo: 'A paciente apresenta asma parcialmente controlada, com baixa adesão à técnica inalatória. Foi substituída a budesonida isolada por budesonida 160 mcg + formoterol 4,5 mcg, 1 inalação 12/12 h. Foi solicitada nova espirometria com prova broncodilatadora e retorno em 6 meses.',
    sinal: 'alterado',
    medidas: [
      { nome: 'Saturação de O2 em ar ambiente', valor: 97, unidade: '%', refMin: 95, sinal: 'normal' },
      { nome: 'Frequência respiratória', valor: 16, unidade: 'irpm', refMin: 12, refMax: 20, sinal: 'normal' },
      { nome: 'Pressão arterial', valor: 134, unidade: 'mmHg', refMax: 140, sinal: 'normal' },
      { nome: 'Pressão arterial', valor: 86, unidade: 'mmHg', refMax: 90, sinal: 'normal' },
      { nome: 'ACT (teste de controle da asma)', valor: 17, unidade: 'pontos', refMin: 20, sinal: 'alterado' },
    ],
    tags: ['asma', 'pneumologia'],
    origem: 'OCR + IA',
    confianca: 0.85,
    documento: '08-consulta-pneumologia-2025-11-04.pdf',
  },
  {
    id: 'd09',
    data: '2026-02-10',
    tipo: 'imagem',
    titulo: 'Ultrassonografia de Abdome Total',
    instituicao: 'Imagem Serra Clara',
    fonte: 'paciente',
    especialidade: 'Radiologia e Diagnóstico por Imagem',
    resumo: 'Foi realizado exame de ultrassonografia de abdome total, que mostrou esteatose hepática leve (grau I) e demais órgãos avaliados sem alterações ecográficas.',
    sinal: 'normal',
    medidas: [
      { nome: 'Dimensão do lobo direito do fígado', valor: 15.2, unidade: 'cm', refMax: 15.5, sinal: 'normal' },
      { nome: 'Diâmetro do colédoco', valor: 4, unidade: 'mm', refMax: 6, sinal: 'normal' },
      { nome: 'Dimensão do baço', valor: 10.8, unidade: 'cm', refMax: 12, sinal: 'normal' },
      { nome: 'Dimensão do rim direito', valor: 10.9, unidade: 'cm', refMin: 9, refMax: 12, sinal: 'normal' },
      { nome: 'Dimensão do rim esquerdo', valor: 11.2, unidade: 'cm', refMin: 9, refMax: 12, sinal: 'normal' },
    ],
    tags: ['ultrassonografia', 'abdome', 'fígado', 'esteatose hepática'],
    origem: 'OCR + IA',
    confianca: 0.7,
    documento: '09-ultrassom-abdome-total-2026-02-10.pdf',
  },
  {
    id: 'f02',
    data: '2026-03-12',
    tipo: 'exame',
    titulo: 'Perfil Lipídico',
    instituicao: 'Laboratório Quaresmeira',
    fonte: 'paciente',
    resumo: 'O exame de perfil lipídico apresentou os seguintes resultados: Colesterol total de 212 mg/dL, LDL-colesterol de 138 mg/dL, HDL-colesterol de 38 mg/dL e Triglicerídeos de 180 mg/dL.',
    sinal: 'alterado',
    medidas: [
      { nome: 'Colesterol total', valor: 212, unidade: 'mg/dL', refMax: 190, sinal: 'alterado' },
      { nome: 'LDL-colesterol', valor: 138, unidade: 'mg/dL', refMax: 130, sinal: 'alterado' },
      { nome: 'HDL-colesterol', valor: 38, unidade: 'mg/dL', refMin: 40, sinal: 'alterado' },
      { nome: 'Triglicerídeos', valor: 180, unidade: 'mg/dL', refMax: 150, sinal: 'alterado' },
    ],
    tags: ['colesterol', 'perfil lipídico'],
    origem: 'OCR + IA',
    confianca: 0.85,
    documento: '02-perfil-lipidico-2026-03-12.pdf',
  },
  { id: 'f09', data: '2026-04-02', tipo: 'documento', titulo: 'Pedido de perfil lipídico', instituicao: 'Clínica Ipê-Roxo', fonte: 'paciente', especialidade: 'Clínica Médica', resumo: 'Pedido de perfil lipídico para controle de dislipidemia em paciente hipertenso.', sinal: 'info', tags: ['perfil lipídico', 'dislipidemia'], origem: 'OCR + IA', confianca: 0.85, documento: '09-pedido-perfil-lipidico-2026-04-02.pdf' },
  {
    id: 'd10',
    data: '2026-05-15',
    tipo: 'exame',
    titulo: 'Hemograma completo e função renal',
    instituicao: 'Laboratório Quaresmeira',
    fonte: 'paciente',
    resumo: 'Resultado do hemograma completo e função renal, com valores de hemácias, hemoglobina, hematócrito, leucócitos totais, eosinófilos, plaquetas, creatinina, taxa de filtração glomerular estimada, ureia e potássio.',
    sinal: 'alterado',
    medidas: [
      { nome: 'Hemácias', valor: 4.52, unidade: 'milhões/μL', refMin: 4.5, refMax: 5.9, sinal: 'normal' },
      { nome: 'Hemoglobina', valor: 13.6, unidade: 'g/dL', refMin: 13.5, refMax: 17.5, sinal: 'normal' },
      { nome: 'Hematócrito', valor: 40.9, unidade: '%', refMin: 41, refMax: 53, sinal: 'alterado' },
      { nome: 'Leucócitos totais', valor: 8.4, unidade: 'mil/μL', refMin: 4, refMax: 11, sinal: 'normal' },
      { nome: 'Eosinófilos', valor: 4.2, unidade: '%', refMin: 1, refMax: 6, sinal: 'normal' },
      { nome: 'Plaquetas', valor: 262, unidade: 'mil/μL', refMin: 150, refMax: 450, sinal: 'normal' },
      { nome: 'Creatinina', valor: 1.08, unidade: 'mg/dL', refMin: 0.7, refMax: 1.3, sinal: 'normal' },
      { nome: 'Taxa de filtração glomerular estimada (TFG)', valor: 85, unidade: 'mL/min/1,73 m²', refMin: 90, sinal: 'alterado' },
      { nome: 'Ureia', valor: 38, unidade: 'mg/dL', refMin: 15, refMax: 45, sinal: 'normal' },
      { nome: 'Potássio', valor: 4.7, unidade: 'mEq/L', refMin: 3.5, refMax: 5.1, sinal: 'normal' },
    ],
    tags: ['hemograma', 'função renal'],
    origem: 'OCR + IA',
    confianca: 0.9,
    documento: '10-hemograma-funcao-renal-2026-05-15.pdf',
  },
  { id: 'd11', data: '2026-07-22', tipo: 'documento', titulo: 'Pedido de ultrassonografia de abdome total', instituicao: 'Clínica Ipê-Roxo', fonte: 'paciente', especialidade: 'Clínica Médica', resumo: 'Pedido de ultrassonografia de abdome total para controle de esteatose hepática em paciente hipertenso e com dislipidemia.', sinal: 'info', tags: ['esteatose hepática', 'hipertensão', 'dislipidemia'], origem: 'OCR + IA', confianca: 0.85, documento: '11-pedido-ultrassom-abdome-2026-07-22.pdf' },
]

export const evento = (id: string) => DEMO_MARCOS.find((e) => e.id === id)!
